### ISSUE TITLE
TypeError: Argument 1 passed to Hyva\Admin\Model\TypeReflection\NamespaceMap

### ISSUE THREAD

**Issue by rav-redchamps** [hyva-themes/hyva-admin-test-module#1]
Hey @Vinai &  @wigman 

Thanks for putting this out.

I just installed in on Magento version 2.4.1 & while accessing admin path System > Tools > Hyvä Test, it returns below error

TypeError: Argument 1 passed to Hyva\Admin\Model\TypeReflection\NamespaceMap::__construct() must be of the type array, string given, 
called in /m2/241/vendor/hyva-themes/module-magento2-admin/Model/TypeReflection/NamespaceMap.php on line 32 
and defined in /m2/241/vendor/hyva-themes/module-magento2-admin/Model/TypeReflection/NamespaceMap.php:14

**Comment by Vinai** [comment]
Hey, thanks for trying out the module and opening the issue.
Turns out, it's an unused constructor argument that got optimized away by Rector PHP during the PHP 7.3 backport.
A new release is coming up in a little while!

**Comment by Vinai** [comment]
Release 1.0.2 pushed - give packagist a few monents to pick it up and you should be good to go.

**Comment by rav-redchamps** [comment]
Thanks @Vinai 

But I still don't see a new release at packagist https://packagist.org/packages/hyva-themes/module-magento2-admin-test it still says dev-main. Possibly the tag hasn't been created for 1.0.2.

**Comment by rav-redchamps** [comment]
Sorry my bad, the release was for main module https://packagist.org/packages/hyva-themes/module-magento2-admin. The problem is resolved now.

**Comment by Vinai** [comment]
Great! 👍🏻
