### ISSUE TITLE
Column(s) not found on source: activity

### ISSUE THREAD

**Issue by rav-redchamps** [hyva-themes/hyva-admin-test-module#2]
Receiving below error when navigation to admin path System > Tools > Hyvä Test.

1 exception(s):
Exception #0 (OutOfBoundsException): Column(s) not found on source: activity

Exception #0 (OutOfBoundsException): Column(s) not found on source: activity
#1 Hyva\Admin\Model\GridSource->extractColumnDefinitions() called at [vendor/hyva-themes/module-magento2-admin/ViewModel/HyvaGridViewModel.php:126]
#2 Hyva\Admin\ViewModel\HyvaGridViewModel->buildColumnDefinitions() called at [vendor/hyva-themes/module-magento2-admin/ViewModel/HyvaGridViewModel.php:116]
#3 Hyva\Admin\ViewModel\HyvaGridViewModel->getAllColumnDefinitions() called at [vendor/hyva-themes/module-magento2-admin/ViewModel/HyvaGridViewModel.php:133]
#4 Hyva\Admin\ViewModel\HyvaGridViewModel->getColumnDefinitions() called at [vendor/hyva-themes/module-magento2-admin/ViewModel/HyvaGridViewModel.php:214]
#5 Hyva\Admin\ViewModel\HyvaGridViewModel->getNavigation() called at [vendor/hyva-themes/module-magento2-admin/view/adminhtml/templates/grid.phtml:7

-----

It gets resolved if I comment out below code in file **vendor/hyva-themes/module-magento2-admin-test/view/adminhtml/hyva-grid/products-grid.xml**

`<column name="activity"/>`

**Comment by Vinai** [comment]
Ah yes, if you install the sample data that attribute exists. I should probably remove that column from the test module.
I’m going to leave the issue open until I do so.
Thanks for reporting!

**Comment by rav-redchamps** [comment]
Yes, definitely. 

Just submitted pull request https://github.com/hyva-themes/hyva-admin-test-module/pull/3 to comment out the line (similar to what's done in filters section). 

Please feel free to let me know if you like me completely remove lines regarding activity column.

**Comment by Vinai** [comment]
Tagged release 1.0.0 of the test module 👍  Thanks again!
