### ISSUE TITLE
Doesn't install on 7.3

### ISSUE THREAD

**Issue by lfolco** [hyva-themes/hyva-admin-test-module#6]
Is this using 7.4-specific features?

**Comment by Vinai** [comment]
I'm not sure.
For the Hyva_Admin module I use rector to backport the main branch to PHP 7.3 for releases, but for the AdminTest module I didn't bother...

**Comment by Vinai** [comment]
I can see the following:

* `\Hyva\AdminTest\Controller\Adminhtml\Test\DumpQueryVars` uses typed properties
* `\Hyva\AdminTest\Model\CustomerArrayProvider` uses typed properties
* `\Hyva\AdminTest\Model\LogFileListProvider` uses typed properties

At first glance the rest looks PHP 7.3 compatible.
It would be trivial to make it PHP 7.3 compatible. I can do that...

**Comment by Vinai** [comment]
Tagged release 1.0.3 which is PHP 7.3 compatible (untested).

**Comment by lfolco** [comment]
Thanks!
